name: ir_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - jieba
  - pip:
      - torch
      - sentence-transformers
      - transformers
      - huggingface-hub
      - rank_bm25
      - python-dotenv
prefix: ./envs/ir_env
